name: Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install scons
        run: python3 -m pip install scons
      - name: Run build
        run: scons
      - name: Run e2e tests
        run: python3 e2e_runner.py
