name: Deploy Doxygen docs to GH pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  get-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changes.outputs.src }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - '.github/workflows/deploy-docs.yml'
              - 'src/**/*.{c,h}'
              - Doxyfile
  build:
    if: needs.get-changes.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Install runtime
        run: sudo apt-get install graphviz doxygen -y
        shell: bash
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Doxygen Documentation
        run: doxygen Doxyfile
      - name: Create .nojekyll (ensures pages with underscores work on gh pages)
        run: touch docs/.nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs'
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.0.10
