name: Deploy Doxygen docs to GH pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  get-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changes.outputs.src }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/**/*.{c,h}'
              - Doxyfile
  deploy:
    if: jobs.get-changes.outputs.changed == 'true'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: get-changes
    runs-on: ubuntu-latest
    steps:
      - name: Install graphviz
        run: sudo apt-get install graphviz -y
        shell: bash
      - uses: DenverCoder1/doxygen-github-pages-action@v1.1.0
        id: deployment
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
